# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          namuwikilover's blog
paginate:       5
baseurl:        ""
url:            "https://namuwikilover.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Chester How
  url:          http://chester.how
  email:        chesterhow@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/Paritta/paritta.github.com

# Gems
gems:
  - jekyll-paginate
